services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    command:
      [
        "uv",
        "run",
        "uvicorn",
        "src.app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
  pg:
    image: postgres:latest
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - ./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    env_file:
      - .env.local
    ports:
      - "6379:6379"

volumes:
  pgdata:
