"""initial

Revision ID: 9d9e73e2a138
Revises: 
Create Date: 2026-04-26 01:17:34.994597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d9e73e2a138'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('job',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialty',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('staff',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tag',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('asker_id', sa.BIGINT(), nullable=True),
    sa.Column('asker_department_id', sa.BIGINT(), nullable=True),
    sa.Column('answerer_id', sa.BIGINT(), nullable=True),
    sa.Column('question', sa.TEXT(), nullable=False),
    sa.Column('answer', sa.TEXT(), nullable=False),
    sa.Column('input_staff_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['answerer_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['asker_department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['asker_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['input_staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_tags',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_tags')
    op.drop_table('question')
    op.drop_table('tag')
    op.drop_table('staff')
    op.drop_table('specialty')
    op.drop_table('job')
    op.drop_table('department')
    # ### end Alembic commands ###
