psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL

CREATE DATABASE "${DB_NAME}"
  LOCALE_PROVIDER = 'icu'
  ICU_LOCALE = 'ja-JP'
  TEMPLATE template0
  ;

ALTER DATABASE ${DB_NAME} SET timezone TO 'Asia/Tokyo';

CREATE USER ${DB_USER} WITH ENCRYPTED PASSWORD '${DB_PASSWORD}';

EOSQL

# 新しいDBでユーザーに権限を付与
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${DB_NAME}" <<-EOSQL

  -- DBへの接続を許可
  GRANT CONNECT ON DATABASE ${DB_NAME} TO ${DB_USER};

  -- スキーマの使用権限
  GRANT USAGE ON SCHEMA public TO ${DB_USER};

  -- 全てのテーブルに対して SELECT, INSERT, UPDATE, DELETE を許可
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${DB_USER};

  -- 今後新しく作成されるテーブルにも自動的に同じ権限を付与する
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DB_USER};

  -- シーケンス（自動採番）の利用を許可
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${DB_USER};

  -- 今後作成されるシーケンスにも自動付与
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ${DB_USER};

EOSQL
